import { Container, Header } from '@/shared/components/shared';

export const metadata = {
  title: 'Next.js Pizza | Cart',
  description: 'Generated by Next.js',
};

export default function CheckoutLayout({ children }: { children: React.ReactNode }) {
  return (
    <main className="min-h-screen bg-[#F4F1EE]">
      <Container>
        <Header hasSearch={false} hasCart={false} className="border-b-grey-200" />
      </Container>
      {children}
    </main>
  );
}
