import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Next pizza | Main',
  description: 'Generated by create next app',
};

export default function HomeLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <main className="min-h-screen">
      {children}
      {modal}
    </main>
  );
}
